# Generated by Django 4.2.6 on 2023-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='courses_taught',
            field=models.ManyToManyField(related_name='courses', to='APIs.course'),
        ),
    ]
