# Generated by Django 4.2.6 on 2023-10-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_instructor_courses_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses_taught',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='instructors', to='APIs.instructor'),
        ),
    ]
